import type { Metadata } from 'next'
import './globals.css'
import {Nav} from './components/Nav'
import "react-toastify/dist/ReactToastify.css"
import ProviderComp from './components/Provider'


export const metadata: Metadata = {
  title: 'Numbers App with Mongo and Redux Persist',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
    <html lang="en">
      
      <body className="flex flex-col bg-white">
      <ProviderComp>
      <Nav />
      {children}
      </ProviderComp>
      </body>
    </html>
    </>
  )
}
